In [15]:
import numpy as np

# This is input layer of 1 and outputlaer of 1
def neural_network(input, weight):
    prediction = inputs.dot(weights)
    return prediction

# Weights
weights = [0.1, 0.2, 0.3] # weights length must equal n inputs


# Data
toes = np.array([8.5, 9.5, 10, 9])
wlrec = np.array([0.65, 0.8, 0.8, 0.99])
nfans = np.array([1.2, 1.5, 0.5, 1.0])


inputs = np.array([number_of_toes[0], wlrec[0], nfans[0]])
pred = neural_network(inputs, weights)

print(pred)

# See notes


1.34


In [19]:
## Section 4 of chapter 3 PT 1 - multipl outputs


def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

# element wise multiplication
def ele_mul(number, vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)








[0.195, 0.13, 0.5850000000000001]


In [13]:
## Section 4 of chapter 3 PT  2 - multipl outputs

# inputs  []float
# weights [][]float
def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred



# multiplay a vector by the matrics
# return a vector equal insize to the input vector
def vect_mat_mul(vector, matrix):
    # Initialilise output to the size of the vector
    output = [0] * len(matrix[0]) # should may size this to based on matrix, row length    
    for i in range(len(vector)):
        # weight sum the vector by each row in the matrix and assigned to vector of ouputs
        output[i] = w_sum(vector, matrix[i])
    return output

# weight sum multiplay each item in a by the corresponding item in b
# a and b must be the same length
# return a single value
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i] # some inputs and weights and accumlate output
    return output

weights = [
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 1.0],
]
toes = [0.65, 0.8, 0.8, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [0.65, 0.8, 0.8, 0.9]

input = [wlrec[0], toes[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)


[-0.065, 0.195, 1.495]


In [14]:
## Section 4 of chapter 3 PT  3 - hidden layers

# inputs  []float
# weights [][]float
def neural_network(input, weights):
    hiddenPred = vect_mat_mul(input, weights[0])   
    pred = vect_mat_mul(hiddenPred, weights[1])
    return pred



# multiplay a vector by the matrics
# return a vector equal insize to the input vector
def vect_mat_mul(vector, matrix):
    # Initialilise output to the size of the vector
    output = [0] * len(matrix[0]) # should may size this to based on matrix, row length    
    for i in range(len(vector)):
        # weight sum the vector by each row in the matrix and assigned to vector of ouputs
        output[i] = w_sum(vector, matrix[i])
    return output

# weight sum multiplay each item in a by the corresponding item in b
# a and b must be the same length
# return a single value
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i] # some inputs and weights and accumlate output
    return output

input_weights = [
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 1.0],
]

hidden_layer_weights = [
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 1.0],
]

weights = [input_weights, hidden_layer_weights]

toes = [0.65, 0.8, 0.8, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [0.65, 0.8, 0.8, 0.9]

input = [wlrec[0], toes[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)


[-0.4355, 0.03250000000000001, 1.7485000000000002]


In [17]:
# Using Numpy

import numpy as np


a = np.array([0,1,2,3]) # create a vector
b = np.array([[0,1,2,3], [4,5,6,7]]) # create a matrix
c = np.zeros((2,4)) # 2 x 4 matrix of zeros
d = np.random.rand(2,5) # 2 x 5 matrixs of values between 0 - 1

print("a", a)
print("b", b)
print("c", c)
print("d", d)

a [0 1 2 3]
b [[0 1 2 3]
 [4 5 6 7]]
c [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
d [[0.58203109 0.72504855 0.12901726 0.41616927 0.47311169]
 [0.10526785 0.43357345 0.47779739 0.4216653  0.35104361]]


In [27]:
# Functions with np
# numpy automatically detects the types its using and tries to resolve the calculat

aMuliplied = a * 0.1 # numpy will do an vecor scaling calculation
print(aMuliplied)


print("---")
# The same is applied to a matrix
bMuliplied = b * 0.1 # matrix scaling
print(  bMuliplied)

print("----")
# Element wise multiplaction occurs when you multiple 2 vectors
a2 = np.array([4,5,6,7])
print(a * a2)


print("-----")
# element wise vector multiplation with a vector and matric
# This can be a tricky one to reason about, its does a * b[i] 
print(a * b)


# The shape must be the same or an error is thrown





[0.  0.1 0.2 0.3]
---
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]
----
[ 0  5 12 21]
-----
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [31]:
# Dot Product
# A weighted sum in np


x = np.zeros((1, 4))
y = np.zeros((4, 3))
z = x.dot(y)

print(x)
print("---")
print(y)
print("----")
print(z.shape)
print(z)


# It is important the neighouring matrixes match, (1,4)(4,3)

[[0. 0. 0. 0.]]
---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----
(1, 3)
[[0. 0. 0.]]


In [33]:
# NN with numpy
import numpy as np
# inputs  []float
# weights [][]float
def neural_network(input, weights):
    hiddenPred = input.dot(weights[0])   
    pred = hiddenPred.dot(weights[1])
    return pred


input_weights = np.array([
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 1.0],
])

hidden_layer_weights = np.array([
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 1.0],
])

weights = np.array([input_weights, hidden_layer_weights])

toes = np.array([0.65, 0.8, 0.8, 0.9])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([0.65, 0.8, 0.8, 0.9])

input = np.array([wlrec[0], toes[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)


[0.117  0.8125 0.416 ]
